@ASPNETCoreWebAPI_HostAddress = http://localhost:5291

GET {{ASPNETCoreWebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ASPNETCoreWebAPI_HostAddress}}/moviereview/
Accept: application/json

###